title: "АЕЦ Козлодуй: Икономически анализ 2025"
description: "Анализ на икономическата траектория на АЕЦ Козлодуй при нарастващ слънчев и акумулаторен капацитет."
lang: bg
theme: minima

minima:
  skin: classic

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-relative-links
